name: open_git
description: "Open-source git client"
publish_to: 'none'
version: 1.0.12+13

environment:
  sdk: ^3.10.0-290.4.beta
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.7
  flutter_bloc: ^9.1.1
  dart_mappable: ^4.6.1
  path: ^1.9.1
  injectable: ^2.7.1+2
  injectable_generator: ^2.11.1
  get_it: ^9.2.0
  shared_preferences: ^2.5.4
  either_dart: ^1.0.0
  logger: ^2.6.2
  flutter_svg: ^2.2.3
  flutter_launcher_icons: ^0.14.4
  package_info_plus: ^9.0.0
  auto_updater: ^1.0.0
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  dart_mappable_builder: ^4.6.3
flutter:
  uses-material-design: true
  assets:
    - assets/file_type_icons/

flutter_launcher_icons:
  image_path: "assets/app_icons/icon.png"
  macos:
    generate: true
    image_path: "assets/app_icons/icon.png"
    